services:
 facefusion-cuda:
  build:
   context: .
   dockerfile: Dockerfile.cuda
  command: [ 'python', 'run.py', '--execution-providers', 'cuda', "--ui-layouts", "webcam"]
  volumes:
  - .assets:/facefusion/.assets
  ports:
  - "7880:7860" # This is your existing rule for the web UI
  deploy:
   resources:
    reservations:
     devices:
     - driver: nvidia
       capabilities: [ gpu, video ]
